GuliEdu/urls.py
from django.conf.urls import url,include
#from django.contrib import admin
import xadmin
from users.views import index #引入index

urlpatterns = [
   # url(r'^admin/', admin.site.urls),
    url(r'^xadmin/', xadmin.site.urls),
    url(r'captcha',include('captcha.urls')),
    url(r'^users/',include('users.urls',namespace='users')),
    url(r'^courses/',include('courses.urls',namespace='courses')),
    url(r'^orgs/',include('orgs.urls',namespace='orgs')),
    url(r'^operations/',include('operations.urls',namespace='operations')),
    url(r'^$',index,name='index')#配置首页
]

apps/courses/urls.py
from django.conf.urls import url
from .views import course_list,course_detail,course_video,course_comment
app_name = 'courses'
urlpatterns = [
    url(r'^course_list/$',course_list,name='course_list'),
    url(r'^course_detail/(\d+)/$', course_detail, name='course_detail'),
    url(r'^course_video/(\d+)/$', course_video, name='course_video'),
    url(r'^course_comment/(\d+)/$', course_comment, name='course_comment'),
]

apps/operations/urls.py
from django.conf.urls import url
from .views import user_ask,user_love,course_comment_list,user_comment
app_name = 'operations'
urlpatterns = [
    url(r'^user_ask/$',user_ask,name='user_ask'),
    url(r'^user_love/$',user_love,name='user_love'),
    url(r'^course_comment_list/(\d+)$', course_comment_list, name='course_comment_list'),
    url(r'^user_comment/$', user_comment, name='user_comment'),
]

apps/courses/models.py
from django.db import models
from datetime import datetime
from orgs.models import OrgInfo,TeacherIfo

# Create your models here.
########################################课程表###########################################
class CourseInfo(models.Model):
    image = models.ImageField(upload_to='course/',max_length=200,verbose_name="课程封面")
    name = models.CharField(max_length=20,verbose_name="课程名称")
    study_time = models.IntegerField(default=0,verbose_name="学习时长")
    study_num = models.IntegerField(default=0,verbose_name="学习人数")
    leave = models.CharField(choices=(('gj',"高级"),('zj',"中级"),('cj',"初级")),max_length=5,verbose_name="课程难度")
    love_num = models.IntegerField(default=0,verbose_name="收藏量")
    click_num = models.IntegerField(default=0,verbose_name="点击量")
    desc = models.CharField(max_length=200,verbose_name="课程简介")
    detail = models.TextField(verbose_name="课程详情")
    category = models.CharField(choices=(('qd',"前端"),('hd',"后端")),max_length=6,verbose_name="课程分类")
    course_notice = models.CharField(max_length=200,verbose_name="课程公告")
    course_need = models.CharField(max_length=200,verbose_name="课程须知")
    teacher_tell = models.CharField(verbose_name="老师告诉你",max_length=200)
    orgInfo = models.ForeignKey(OrgInfo,verbose_name="所属机构",on_delete=models.CASCADE)
    teacherIfo = models.ForeignKey(TeacherIfo,verbose_name="所属讲师",on_delete=models.CASCADE)
    add_time = models.DateTimeField(default=datetime.now,verbose_name="创建时间")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "课程信息"
        verbose_name_plural = verbose_name

class LessonInfo(models.Model):
    name = models.CharField(verbose_name="章节名称",max_length=10)
    courseInfo = models.ForeignKey(CourseInfo,verbose_name="所属课程",on_delete=models.CASCADE)
    add_time = models.DateTimeField(default=datetime.now, verbose_name="创建时间")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "章节信息"
        verbose_name_plural = verbose_name

class videoInfo(models.Model):
    name = models.CharField(verbose_name="视频名称", max_length=10)
    study_time = models.IntegerField(default=0,verbose_name="视频时长")
    lessonInfo = models.ForeignKey(LessonInfo,verbose_name="所属章节",on_delete=models.CASCADE)
    url = models.URLField(default='http://www.atguigu.com',verbose_name="视频连接",max_length=200)
    add_time = models.DateTimeField(default=datetime.now, verbose_name="创建时间")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "视频信息"
        verbose_name_plural = verbose_name


class SourceInfo(models.Model):
    name = models.CharField(verbose_name="资源名称",max_length=50)
    down_load = models.FileField(upload_to='source/',verbose_name="下载路径",max_length=200)
    courseInfo = models.ForeignKey(CourseInfo,verbose_name="所属课程",on_delete=models.CASCADE)
    add_time = models.DateTimeField(default=datetime.now, verbose_name="创建时间")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "资源信息"
        verbose_name_plural = verbose_name

apps/operations/models.py
from datetime import datetime

from django.db import models

from users.models import UserProfile
from courses.models import CourseInfo

# Create your models here.

class UserAsk(models.Model):
    name = models.CharField(verbose_name="姓名",max_length=30)
    phone = models.CharField(verbose_name="手机号",max_length=11)
    course = models.CharField(verbose_name="课程",max_length=20)
    add_time = models.DateTimeField(default=datetime.now,verbose_name="创建时间")

    def __str__(self):
        return  self.name

    class Meta :
        verbose_name = "咨询信息"
        verbose_name_plural = verbose_name

class UserLove(models.Model):
    love_man = models.ForeignKey(UserProfile,verbose_name="收藏用户",on_delete=models.CASCADE)
    love_id = models.IntegerField(verbose_name="收藏的id")
    love_type = models.IntegerField(choices=((1,'org'),(2,'course'),(3,'teacher')),verbose_name="收藏类别")
    love_status = models.BooleanField(default=False,verbose_name="收藏状态")
    add_time = models.DateTimeField(default=datetime.now, verbose_name="收藏时间")

    def __str__(self):
        return  self.love_man.username

    class Meta :
        verbose_name = "收藏信息"
        verbose_name_plural = verbose_name

class UserCourse(models.Model):
    study_man = models.ForeignKey(UserProfile,verbose_name="学习用户",on_delete=models.CASCADE)
    study_course = models.ForeignKey(CourseInfo,verbose_name="学习课程",on_delete=models.CASCADE)
    add_time = models.DateTimeField(default=datetime.now, verbose_name="收藏时间")

    def __str__(self):
        return  self.study_man.username

    class Meta :
        unique_together = ('study_man','study_course')#去重，再次学习这个课程不添加数据
        verbose_name = "用户学习课程信息"
        verbose_name_plural = verbose_name

class UserComment(models.Model):
    comment_man = models.ForeignKey(UserProfile, verbose_name="评论用户",on_delete=models.CASCADE)
    comment_course = models.ForeignKey(CourseInfo, verbose_name="评论课程",on_delete=models.CASCADE)
    comment_content = models.CharField(verbose_name="评论内容",max_length=300)
    add_time = models.DateTimeField(default=datetime.now, verbose_name="评论时间")

    def __str__(self):
        return self.comment_man.username

    class Meta:
        verbose_name = "用户评论课程信息"
        verbose_name_plural = verbose_name

class UserMessage(models.Model):
    message_man = models.IntegerField(default=0,verbose_name="消息用户")#0=系统消息；
    message_content = models.CharField(verbose_name="消息内容",max_length=200)
    message_status = models.BooleanField(default=False,verbose_name="消息状态")
    add_time = models.DateTimeField(default=datetime.now, verbose_name="消息时间")

    def __str__(self):
        return self.message_content

    class Meta:
        verbose_name = "用户消息"
        verbose_name_plural = verbose_name

apps/orgs/models.py
from django.db import models
from datetime import  datetime
# Create your models here.
################################城市###################################################
class CityInfo(models.Model):
    name = models.CharField(max_length=20,verbose_name="城市名称")
    add_time = models.DateTimeField(default=datetime.now,verbose_name="添加时间")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '城市信息'
        verbose_name_plural = verbose_name
##############################机构#####################################################
class OrgInfo(models.Model):
    image = models.ImageField(upload_to='org/',max_length=200,verbose_name='机构封面')
    name = models.CharField(max_length=20,verbose_name="机构名称")
    course_num = models.IntegerField(default=0,verbose_name="课程数")
    study_num = models.IntegerField(default=0,verbose_name="学习人数")
    address = models.CharField(max_length=200,verbose_name="机构地址")
    desc = models.CharField(max_length=200,verbose_name="机构简介")
    detail = models.TextField(verbose_name="机构详情")
    love_num = models.IntegerField(default=0,verbose_name="收藏数")
    click_num = models.IntegerField(default=0,verbose_name="点击数")
    category = models.CharField(choices=(('pxjg',"培训机构"),('gx',"高校"),('gr',"个人")),max_length=10,verbose_name='机构类别')
    add_time = models.DateTimeField(default=datetime.now, verbose_name="创建时间")
    cityinfo = models.ForeignKey(CityInfo,verbose_name="所在城市",on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "机构信息"
        verbose_name_plural = verbose_name
#####################################教师表############################################
class TeacherIfo(models.Model):
    image = models.ImageField(upload_to='teacher/',max_length=200,verbose_name="讲师头像")
    name = models.CharField(max_length=20,verbose_name="讲师姓名")
    work_year = models.IntegerField(default=3,verbose_name="工作年限")
    work_position = models.CharField(max_length=30,verbose_name="职位")
    work_style = models.CharField(max_length=20,verbose_name="教学特点")
    work_company = models.ForeignKey(OrgInfo,verbose_name="所属机构",on_delete=models.CASCADE)
    age = models.IntegerField(default=30,verbose_name="讲师年龄")
    gender = models.CharField(choices=(('boy',"男"),('gril',"女")),max_length=10,verbose_name="讲师性别",default='boy')
    love_num = models.IntegerField(default=0, verbose_name="收藏数")
    click_num = models.IntegerField(default=0, verbose_name="点击数")

    def __str__(self):
        return self.name

    class Meta :
        verbose_name = "讲师信息"
        verbose_name_plural = verbose_name

apps/courses/views.py
from django.shortcuts import render
from .models import CourseInfo
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from operations.models import UserLove,UserCourse
# Create your views here.

def course_list(request):

    #获取所有课程
    all_course = CourseInfo.objects.all()

    #获取推荐的(按时间倒序)
    recomend_courses = all_course.order_by('-add_time')[:3]

    sort = request.GET.get('sort','')
    if sort:
        all_course.order_by('-'+sort)

    # 分页代码
    pagenum = request.GET.get('pagenum', '')
    pa = Paginator(all_course, 3)
    try:
        pages = pa.page(pagenum)
    except PageNotAnInteger:
        pages = pa.page(1)
    except EmptyPage:
        pages = pa.page(pa.num_pages)

    return render(request,'courses/course-list.html',{
        'pages':pages,
        'recomend_courses':recomend_courses,
    })

def course_detail(request,id):
    if id:
        course = CourseInfo.objects.filter(id=int(id))[0]
        # 获取相关课程 exclude()排除自己
        re_course = CourseInfo.objects.filter(category=course.category).exclude(id=int(course.id))[:2]
        lovecourse = False
        loveorg = False
        if request.user.is_authenticated():
            love = UserLove.objects.filter(love_id=int(id),love_type=2,love_status=True,love_man=request.user)
            if love:
                lovecourse = True
            love = UserLove.objects.filter(love_id=course.orgInfo.id, love_type=1, love_status=True, love_man=request.user)
            if love:
                loveorg = True
        return  render(request,'courses/course-detail.html',{
            'course':course,
            're_course':re_course,
            'lovecourse':lovecourse,
            'loveorg':loveorg
        })

def course_video(request,course_id):
    if course_id:
        course = CourseInfo.objects.filter(id=int(course_id))[0]
        #当用户点击学习时,代表该用户学习了该课程，如果没有学习则加上学习操作
        usercourse_list = UserCourse.objects.filter(study_course=course,study_man=request.user)
        if not usercourse_list:
            a = UserCourse()
            a.study_man = request.user
            a.study_course = course
            a.save()

        #学过该课程的学生还学过什么
        usercourse_list = UserCourse.objects.filter(study_course=course)
        #列表生成式
        user_list = [usercourse.study_man for usercourse in usercourse_list]
        #__in:在哪个范围内
        # exclude去除...
        usercourse_list = UserCourse.objects.filter(study_man__in=user_list).exclude(study_course=course)
        # 拿到课程
        # set()用于去重
        course_list = list(set([usercourse.study_course for usercourse in usercourse_list]))

        return render(request,'courses/course-video.html',{
            'course':course,
            'course_list':course_list
        })

def course_comment(request,course_id):
    if course_id:
        course = CourseInfo.objects.filter(course_id=int(course_id))[0]

        course = CourseInfo.objects.filter(id=int(course_id))[0]
        # 当用户点击学习时,代表该用户学习了该课程，如果没有学习则加上学习操作
        usercourse_list = UserCourse.objects.filter(study_course=course, study_man=request.user)
        if not usercourse_list:
            a = UserCourse()
            a.study_man = request.user
            a.study_course = course
            a.save()

        # 学过该课程的学生还学过什么
        usercourse_list = UserCourse.objects.filter(study_course=course)
        # 列表生成式
        user_list = [usercourse.study_man for usercourse in usercourse_list]
        # __in:在哪个范围内
        # exclude去除...
        usercourse_list = UserCourse.objects.filter(study_man__in=user_list).exclude(study_course=course)
        # 拿到课程
        # set()用于去重
        course_list = list(set([usercourse.study_course for usercourse in usercourse_list]))

        return render(request, 'courses/course-comment.html', {
            'course': course,
            'course_list':course_list
        })

templates/courses/course-comment.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}
    公开课评论 - 谷粒教育网
{% endblock %}

{% block mycss %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/guli/course/learn-less.css' %}" />
	<link rel="stylesheet" type="text/css" href="{% static 'css/guli/course/course-comment.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/guli/base.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/guli/common-less.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/guli/course/common-less.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/mooc.css' %}" />
{% endblock %}

{% block  content%}
    <section>
        <div class="wp">
            <div class="crumbs">
                <ul>
                    <li><a href="/">首页</a>></li>
                    <li><a href="{% url 'courses:course_list' %}">公开课程</a>></li>
                    <li><a href="{% url 'courses:course_detail' course.id %}">课程详情</a>></li>
                    <li>课程评论</li>
                </ul>
            </div>
        </div>
    </section>

    <div id="main">
        <div class="course-infos">
            <div class="w pr">
                <div style="height: 15px" class="path">
                </div>
                <div class="hd">
                    <h2 class="l">{{ course.name }}</h2>
                </div>
                <div class="statics clearfix">
                    <div class="static-item ">
                        <span class="meta-value">
                            <strong>
                                {% if course.leave == 'gj' %}
                                    高级
                                {% elif course.leave == 'zj' %}
                                    中级
                                {% elif course.leave == 'cj' %}
                                    初级
                                {% endif %}
                            </strong>
                        </span>
                        <span class="meta">难度</span>
                        <em></em>
                    </div>
                    <div class="static-item static-time">
                        <span class="meta-value">{{ course.study_time }}</span>
                        <span class="meta">时长</span>
                        <em></em>
                    </div>
                    <div class="static-item">
                        <span class="meta-value"><strong>{{ course.study_num }}</strong></span>
                        <span class="meta">学习人数</span>
                        <em></em>
                    </div>
                </div>
            </div>
        </div>
        <div class="course-info-main clearfix w has-progress">

            <div class="info-bar clearfix">
                <div class="content-wrap clearfix">
                    <div class="content">
                        <div class="mod-tab-menu">
                            <ul class="course-menu clearfix">
                                <li><a class="ui-tabs-active " id="learnOn"  href="{% url 'courses:course_detail' course.id %}"><span>章节</span></a></li>
                                <li><a id="commentOn" class="active" href="{% url 'operations:course_comment_list' course.id %}"><span>评论</span></a></li>
                            </ul>
                        </div>

                        <!--发布评论-->
                        <div id="js-pub-container" class="issques clearfix js-form">
                            <div class="wgt-ipt-wrap pub-editor-wrap " id="js-pl-input-fake">
                                <textarea id="js-pl-textarea" class="" placeholder="扯淡、吐槽、表扬、鼓励……想说啥就说啥！" ></textarea>
                            </div>
                            <input type="button" id="js-pl-submit" class="pub-btn" data-cid="452" value="发表评论">
                            <p class="global-errortip js-global-error"></p>
                        </div>
                        <div id="course_note">
                            <ul class="mod-post" id="comment-list">
                                {% for comment in comment_list %}
                                    <li class="post-row">
                                    <div class="media">
                                        <span target="_blank"><img src='{{ MEDIA_URL }}{{ comment.comment_man.image }}' width='40' height='40' /></span>
                                    </div>
                                    <div class="bd">
                                        <div class="tit">
                                            <span target="_blank">{{ comment.comment_man.nick_name }}</span>
                                        </div>
                                        <p class="cnt">{{ comment.comment_content }}</p>
                                        <div class="footer clearfix">
                                            <span title="创建时间" class="l timeago">时间：{{ comment.add_time }}</span>
                                        </div>
                                    </div>
                                </li>
                                {% endfor %}

                            </ul>
                        </div>

                    </div>
                    <div class="aside r">
                        <div class="bd">

                            <div class="box mb40">
                            <h4>资料下载</h4>
                            <ul class="downlist">
                                {% for source in course.sourceinfo_set.all %}
                                    <li>
                                        <span ><i class="aui-iconfont aui-icon-file"></i>{{ source.name }}</span>
                                        <a href="{{ MEDIA_URL }}{{ source.down_load }}" class="downcode" target="_blank" download="" data-id="274" title="">下载</a>
                                    </li>
                                {% endfor %}
                            </ul>
                        </div>
                            <div class="box mb40">
                            <h4>讲师提示</h4>
                            <div class="teacher-info">
                                <a href="/u/315464/courses?sort=publish" target="_blank">
                                    <img src='{{ MEDIA_URL }}{{ course.teacherIfo.image }}' width='80' height='80' />
                                </a>
            <span class="tit">
              <a href="/u/315464/courses?sort=publish" target="_blank">{{ course.teacherIfo.name }}</a>
            </span>
                                <span class="job">{{ course.teacherIfo.work_position }}</span>
                            </div>
                            <div class="course-info-tip">
                                <dl class="first">
                                    <dt>课程须知</dt>
                                    <dd class="autowrap">{{ course.course_need }}</dd>
                                </dl>
                                <dl>
                                    <dt>老师告诉你能学到什么？</dt>
                                    <dd class="autowrap">{{ course.teacher_tell }}</dd>
                                </dl>
                            </div>
                        </div>


                            <div class="cp-other-learned  js-comp-tabs">
                                <div class="cp-header clearfix">
                                    <h2 class="cp-tit l">该课的同学还学过</h2>
                                </div>
                                <div class="cp-body">
                                    <div class="cp-tab-pannel js-comp-tab-pannel" data-pannel="course" style="display: block">
                                        <!-- img 200 x 112 -->
                                        <ul class="other-list">
                                            {% for course in course_list %}
                                                <li class="curr">
                                                    <a href="{% url 'courses:course_detail' course.id %}" target="_blank">
                                                        <img src="{{ MEDIA_URL }}{{ course.image }}" alt="html">
                                                        <span class="name autowrap">{{ course.name }}</span>
                                                    </a>
                                                </li>
                                            {% endfor %}
                                        </ul>
                                    </div>

                                </div>
                            </div>

                        </div>    </div>
                </div>
                <div class="clear"></div>
            </div>
        </div>
    </div>
{% endblock %}

{% block myjs %}
    <script>
        $(function () {
            {% comment %} 发表评论 {% endcomment %}
            $('#js-pl-submit').click(function () {
                var course = {{ course.id }}
                var content = $('#js-pl-textarea').val()

                $.ajax({
                    url:'{% url 'operations:user_comment' %}',
                    type:'POST',
                    data:{
                        'course':course,
                        'content':content,
                        'csrfmiddlewaretoken':'{{ csrf_token }}'
                    },
                    success:function (callback) {
                        if(callback.status == 'ok'){
                            alert(callback.msg)
                            window.location.reload();
                        }else {
                            alert(callback.msg)
                        }
                    }
                })
            })
        })
    </script>
{% endblock %}

templates/courses/course-detail.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}
    公开课详情 - 谷粒教育网
{% endblock %}

{% block content %}
    <section>
	<div class="wp">
		<div class="crumbs">
			<ul>
				<li><a href="index.html">首页</a>></li>
                <li><a href="">公开课程</a>></li>
				<li>课程详情</li>
			</ul>
		</div>
	</div>
</section>
    <section>
	<div class="wp">
		<div class="groupPurchase_detail detail">
			<div class="toppro">
				<div class="left">
					<div class="picbox">
						<div class="tb-booth tb-pic">
							<img width="440" height="445" src="{{ MEDIA_URL }}{{ course.image }}" class="jqzoom" />
						</div>

					</div>
					<div class="des">
						<h1 title="mysql基础">123</h1>
						<span class="key">123</span>
						<div class="prize">
							<span class="fl">难度：<i class="key">{% if course.leave == 'gj' %}高级{% elif course.leave == 'zj' %}中级{% elif course.leave == 'cj' %}初级{% endif %}</i></span>
							<span class="fr">学习人数：{{ course.study_num }}</span>
						</div>
						<ul class="parameter">
							<li><span class="pram word3">时&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;长：</span><span>{{ course.study_time }}</span></li>
                            <li><span class="pram word3">章&nbsp;节&nbsp;数：</span><span>5</span></li>
                            <li><span class="pram word3">课程类别：</span><span title="">{% if course.category == 'qd' %}前端{% elif course.category == 'hd' %}后端{% endif %}</span></li>
							<li class="piclist"><span class="pram word4">学习用户：</span>
                                {% for usercourse in course.usercourse_set.all|slice:":6" %}
                                    <span class="pic"><img width="40" height="40" src="{{ MEDIA_URL }}{{ usercourse.study_man.image }}"/></span>
                                {% endfor %}
							</li>
						</ul>
						<div class="btns">
							<div class="btn colectgroupbtn"  id="jsLeftBtn">
                                {% if lovecourse %}
                                    取消收藏
                                {% else %}
                                    收藏
                                {% endif %}
                            </div>
                                <div class="buy btn"><a style="color: white" href="{% url 'courses:course_video' course.id %}">开始学习</a></div>
						</div>
					</div>
				</div>
				<div class="right">
					<div class="head">
						<h1>授课机构</h1>
						<p>世界名校，课程权威</p>
					</div>
					<div class="pic">
                        <a href="">
                            <img width="150" height="80" src="{{ MEDIA_URL }}{{ course.orgInfo.image }}"/>
                        </a>
                    </div>
					<a href="">
                        <h2 class="center" title="{{ course.orgInfo.name }}">{{ course.orgInfo.name }}</h2>
                    </a>
					<div class="btn  notlogin" data-favid="14" id="jsRightBtn">
                         {% if loveorg %}
                            取消收藏
                         {% else %}
                            收藏
                         {% endif %}
                    </div>
					<div class="clear">
						<ul>
                            <li>
                                <span>课 &nbsp;程&nbsp; 数：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;   {{ course.orgInfo.course_num }}</span>
                            </li>
                            <li>
                                <span>教 &nbsp;师&nbsp; 数：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  {{ course.orgInfo.teacherifo_set.count }}</span>
                            </li>
							<li>所在地区：&nbsp;&nbsp;{{ course.orgInfo.cityinfo.name }}</li>
							<li>认&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;证&nbsp;:
                                &nbsp;&nbsp;
								    <img title="金牌机构" src="{% static 'images/gold.png' %}"/>
							</li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
    <section>
	<div class="wp">
		<div class="list groupPurchase_detail_pro">
			<div class="left layout">
				<div class="head">
					<ul class="tab_header">
						<li class="active">课程详情</li>
					</ul>
				</div>
				<div class="tab_cont tab_cont1">
					<p> {{ course.detail }}</p>
				</div>
				<div class="tab_cont tab_cont2" >
					<div class="comment">
						<div class="comenlist">

	                    </div>
					</div>
				</div>
			</div>
			<div class="right layout">
				<div class="head">相关课程推荐</div>
                <div class="group_recommend">
                    {% if re_course %}

                        {% else  %}
                            {% for re in re_course %}
                                <dl>
                                    <dt>
                                        <a target="_blank" href="{% url 'courses:course_detail' re.id %}">
                                         <img width="240" height="220" class="scrollLoading" src="{{ MEDIA_URL }}{{ re.image }}"/>
                                        </a>
                                 </dt>
                                 <dd>
                                        <a target="_blank" href=""><h2>{{ re.name }}</h2></a>
                                        <span class="fl">学习时长：{{ re.study_time }}<i class="key"></i></span>
                                    </dd>
                                </dl>
                            {% endfor %}
                    {% endif %}

                </div>
			</div>
		</div>
	</div>
</section>
{% endblock %}
{% block myjs %}
    <script>
        $(function () {
            {% comment %}收藏课程{% endcomment %}
            $('#jsLeftBtn').click(function () {
                var love_id = {{ course.id }}
                var love_type = 2
                $.ajax({
                    url:'{% url 'operations:user_love' %}',
                    type:'GET',
                    data:{
                        'love_id':love_id,
                        'love_type':love_type
                    },
                    success:function (callback) {
                        if(callback.status == 'ok'){
                            $('#jsLeftBtn').text(callback.msg)
                        }else {
                            alert(callback.msg)
                        }
                    }
                })
            });

            {% comment %}收藏机构{% endcomment %}
            $('#jsRightBtn').click(function (callback) {
                var love_id = {{ course.orgInfo.id}}
                var love_type = 1
                $.ajax({
                    url:'{% url 'operations:user_love' %}',
                    type:'GET',
                    data:{
                        'love_id':love_id,
                        'love_type':love_type
                    },
                    success:function (callback) {
                        if(callback.status == 'ok'){
                            $('#jsRightBtn').text(callback.msg)
                        }else {
                            alert(callback.msg)
                        }
                    }
                })
            });
        })
    
    </script>
{% endblock %}