GuliEdu/urls.py
from django.conf.urls import url,include
#from django.contrib import admin
import xadmin
from users.views import index #引入index

urlpatterns = [
   # url(r'^admin/', admin.site.urls),
    url(r'^xadmin/', xadmin.site.urls),
    url(r'captcha',include('captcha.urls')),
    url(r'^users/',include('users.urls',namespace='users')),
    url(r'^courses/',include('courses.urls',namespace='courses')),
    url(r'^orgs/',include('orgs.urls',namespace='orgs')),
    url(r'^operations/',include('operations.urls',namespace='operations')),
    url(r'^$',index,name='index')#配置首页
]

apps/users/urls.py
from django.conf.urls import url
from .views import user_register,user_login,user_logout,user_active,user_info,user_change_image
app_name = 'users'
urlpatterns = [
    url(r'^user_register/$',user_register,name="user_register"),#注册url
    url(r'^user_login/$',user_login,name='user_login'),
    url(r'^user_logout/$',user_logout,name='user_logout'),
    url(r'^user_active/(\w+)/$',user_active,name='user_active'), # (\w+)捕获传递的参数
    url(r'^user_info/$',user_info,name='user_info'),
    url(r'^user_change_image/$',user_change_image,name='user_change_image'),
]

apps/users/models.py
from datetime import datetime

from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.
class UserProfile(AbstractUser) :
    #头像
    image = models.ImageField(upload_to='user/',max_length=200,verbose_name="用户头像",null=True,blank=True)
    #昵称
    nick_name = models.CharField(max_length=20,verbose_name="用户昵称",null=True,blank=True)
    #生日
    birthday = models.DateTimeField(verbose_name="用户生日",null=True,blank=True)
    #性别
    gender = models.CharField(choices=(('girl','女'),('boy','男')),max_length=10,verbose_name="用户性别",default='gril')
    #会员地址
    address = models.CharField(max_length=20,verbose_name="地址",null=True,blank=True)
    #会奥运手机
    phone = models.CharField(max_length=11,verbose_name="用户手机",null=True,blank=True)
    #创建时间
    add_time = models.DateTimeField(default=datetime.now,verbose_name="创建时间")
    #控制是否激活
    is_start = models.BooleanField(default=False,verbose_name="是否激活")

    def __str__(self):
        return self.username

    class Meta :
        verbose_name = '用户信息'
        verbose_name_plural = verbose_name
########################################################################################################################
    #轮播
class BannerInfo(models.Model) :
    #轮播图片
    image = models.ImageField(upload_to='banner/',verbose_name="轮播图片",max_length=200)
    #链接地址
    url = models.URLField(default='http://www.atguigu.com',verbose_name="图片链接",max_length=200)
    # 创建时间
    add_time = models.DateTimeField(default=datetime.now, verbose_name="创建时间")

    def __str__(self):
        return str(self.image)

    class Meta:
        verbose_name = '轮播图信息'
        verbose_name_plural = verbose_name
########################################################################################################################
#邮箱验证
class EmailVerifyCode(models.Model) :
    code = models.CharField(max_length=20,verbose_name="邮箱验证码")
    email = models.EmailField(max_length=200,verbose_name="验证邮箱")
    send_type = models.IntegerField(choices=((1,'register'),(2,'forger'),(3,'change')),verbose_name="验证码类型")
    add_time = models.DateTimeField(default=datetime.now, verbose_name="创建时间")

    def __str__(self):
        return self.code

    class Meta:
            verbose_name = '验证码信息'
            verbose_name_plural = verbose_name

apps/users/forms.py
from django import forms
from captcha.fields import CaptchaField
from .models import UserProfile

class UserRegisterForm(forms.Form):
    #验证邮箱
    email = forms.EmailField(required=True)
    #密码
    password = forms.CharField(required=True,min_length=3,max_length=15,
                               error_messages={
                                   'required':'密码必须填写',
                                   'min_length':'密码必须大于3位',
                                   'max_length':'密码最长为15位'
                                    }
                               )
    # captcha邀请码
    captcha = CaptchaField()
class UserLoginForm(forms.Form):
    #验证邮箱
    email = forms.EmailField(required=True)
    #密码
    password = forms.CharField(required=True,min_length=3,max_length=15,
                               error_messages={
                                   'required':'密码必须填写',
                                   'min_length':'密码必须大于3位',
                                   'max_length':'密码最长为15位'
                                    }
                               )
class UserChangeImageForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['image']

apps/users/views.py
from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import render, redirect, reverse
from .forms import UserRegisterForm, UserLoginForm,UserChangeImageForm
from .models import UserProfile, EmailVerifyCode
from django.contrib.auth import authenticate, login, logout
from utils.SendEmailUtil import SendEmailUtil
from .models import EmailVerifyCode
from django.http import JsonResponse
# Create your views here.
# 跳转首页


def index(request):
    return render(request, 'index.html')

############################用户注册##########################################
# @csrf_exempt 此标签取消验证


def user_register(request):
    if request.method == 'GET':  # get请求是跳页面
        # 这里实例化form，不是为了验证,而是为了验证验证码
        user_register_form = UserRegisterForm()
        return render(request, 'users/register.html', {
            'user_register_form': user_register_form
        })
    else:
        user_register_form = UserRegisterForm(request.POST)
        if user_register_form.is_valid():
            email = user_register_form.cleaned_data['email']
            password = user_register_form.cleaned_data['password']

            user_list = UserProfile.objects.filter(
                Q(username=email) | Q(email=email))
            if user_list:
                return render(request, 'users/register.html',
                              {'msg': '用户已经存在'})
            else:
                user = UserProfile()
                user.username = email
                user.email = email
                user.set_password(password)
                user.save()
                # 发送邮件
                SendEmailUtil.sendEmail(email=email, send_type=1)
                return HttpResponse('请尽快激活您的邮箱，否则无法登陆。')
        else:
            return render(request, 'users/register.html',
                          {'user_register_form': user_register_form})
############################用户注册##########################################

############################用户登录##########################################


def user_login(request):
    if request.method == 'GET':
        return render(request, 'users/login.html')
    else:
        user_login_form = UserLoginForm(request.POST)
        if user_login_form.is_valid():
            email = user_login_form.cleaned_data['email']
            password = user_login_form.cleaned_data['password']

            # 查询是否有
            user = authenticate(username=email, password=password)
            if user:
                if user.is_start:
                    login(request, user)
                    return redirect(reverse('index'))
                else:
                    return HttpResponse('请去你的邮箱激活，否则无法登陆')
            else:
                return render(request, 'users/login.html', {
                    'msg': '邮箱或者密码有误'
                })
        else:
            return render(request, 'users/login.html',
                          {'user_login_form': user_login_form})

##################################退出######################################


def user_logout(request):
    logout(request)
    return redirect(reverse('index'))


def user_active(request, code):
    # 获取code
    if code:
        # 根据code获取Email列表
        email_var_list = EmailVerifyCode.objects.filter(code=code)
        if email_var_list:
            # 获取第一个
            email_var = email_var_list[0]
            # 获取email
            email = email_var.email
            # 根据email获取用户
            user_list = UserProfile.objects.filter(username=email)
            if user_list:
                user = user_list[0]
                # 更改用户状态为激活状态
                user.is_start = True
                user.save()
                return redirect(reverse('users:user_login'))
            else:
                pass
        else:
            pass
    else:
        pass

def user_info(request):
    return render(request,'users/usercenter-info.html')

def user_change_image(request):
    # request.FILES 获取文件
    # instance=我传过来的是当前用户的示例,通常代表着修改哪个对象(要修改必须加上instance)
    user_change_image_form = UserChangeImageForm(request.POST,request.FILES,instance=request.user)
    if user_change_image_form.is_valid():
        user_change_image_form.save(commit=True)
        return JsonResponse({'status': 'ok'})
    else:
        return JsonResponse({'status': 'fail'})

templates/users/login.html
<!DOCTYPE html>
{% load staticfiles %}
<html>

<head>
	<meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" >
	<title>谷粒教育在线网登录</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}">
</head>
<body>
<header>
    <div class="c-box fff-box">
        <div class="wp header-box">
            <p class="fl hd-tips">谷粒教育在线网，在线学习平台！</p>
            <ul class="fr hd-bar">
                <li>服务电话：<span>88888888</span></li>
                <li class="active"><a href="login.html">[登录]</a></li>
                <li><a href="register.html">[注册]</a></li>
            </ul>
        </div>
    </div>
</header>
<section>
    <div class="c-box bg-box">
        <div class="login-box clearfix">
            <div class="hd-login clearfix">
                <a class="index-logo" href="index.html"></a>
                <h1>用户登录</h1>
                <a class="index-font" href="index.html">回到首页</a>
            </div>
            <div class="fl slide">
                <div class="imgslide">
                    <ul class="imgs">
                            <li><a href=""><img width="483" height="472" src="{% static 'images/mysql.jpg' %}" /></a></li>
                            <li><a href=""><img width="483" height="472" src="{% static 'images/mongoDB.jpg' %}" /></a></li>
                            <li><a href=""><img width="483" height="472" src="{% static 'images/mysql.jpg' %}" /></a></li>
                    </ul>
                </div>
                <div class="unslider-arrow prev"></div>
                <div class="unslider-arrow next"></div>
            </div>
            <div class="fl form-box">
                <h2>帐号登录</h2>
                <form action="{% url 'users:user_login' %}" method="post" autocomplete="off">
                    {% csrf_token %}
                    <div class="form-group marb20 ">
                        <label>用&nbsp;户&nbsp;名</label>
                        <input name="email" id="account_l" type="text" placeholder="手机号/邮箱" />
                    </div>
                    <div class="form-group marb8 ">
                        <label>密&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;码</label>
                        <input name="password" id="password_l" type="password" placeholder="请输入您的密码" />
                    </div>
                    <div class="error btns login-form-tips" id="jsLoginTips">
                        {{ msg }}
                            {% for key,err in user_register_form.errors.items %}
                                {{ err }}
                            {% endfor %}
                    </div>
                     <div class="auto-box marb38">

                        <a class="fr" href="forgetpwd.html">忘记密码？</a>
                     </div>
                     <input class="btn btn-green" id="jsLoginBtn" type="submit" value="立即登录 > " />
                </form>
                <p class="form-p">没有谷粒教育在线网帐号？<a href="register.html">[立即注册]</a></p>
            </div>
        </div>
    </div>
</section>
<script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/unslider.js' %}" type="text/javascript"></script>
<script src="{% static 'js/login.js' %}"  type="text/javascript"></script>
</body>
</html>

templates/users/register.html
<!DOCTYPE html>
{% load staticfiles %}{% comment %}引入静态文件{% endcomment %}
<html>
<head>
    <meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" >
    <title>谷粒教育注册</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}">

</head>
<body>

<header>
    <div class="c-box fff-box">
        <div class="wp header-box">
            <p class="fl hd-tips">谷粒教育，在线学习平台！</p>
            <ul class="fr hd-bar">
                <li>服务电话：<span>88888888</span></li>
                <li><a href="login.html">[登录]</a></li>
                <li class="active"><a href="register.html">[注册]</a></li>
            </ul>
        </div>
    </div>
</header>
<section>
    <div class="c-box bg-box">
        <div class="login-box clearfix">
            <div class="hd-login clearfix">
                <a class="index-logo" href="index.html"></a>
                <h1>用户注册</h1>
                <a class="index-font" href="index.html">回到首页</a>
            </div>
            <div class="fl slide">
                <div class="imgslide">
                    <ul class="imgs">

                        <li><a href=""><img width="483" height="472" src="{% static 'images/mysql.jpg' %}" /></a></li>

                        <li><a href=""><img width="483" height="472" src="{% static 'images/mongoDB.jpg' %}" /></a></li>

                        <li><a href=""><img width="483" height="472" src="{% static 'images/mysql.jpg' %}" /></a></li>

                    </ul>
                </div>
                <div class="unslider-arrow prev"></div>
                <div class="unslider-arrow next"></div>
            </div>
            <div class="fl form-box">
                <div class="tab">
                    <h2>邮箱注册</h2>
                </div>
                
                <div class="tab-form">
                    <form id="email_register_form" method="post" action="{% url 'users:user_register' %}" autocomplete="off">{% csrf_token %}{% comment %}必须加{% endcomment %}
                        <div class="form-group marb20 ">
                            <label>邮&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;箱</label>
                            <input  type="text" id="id_email" name="email" value="None" placeholder="请输入您的邮箱地址" />
                        </div>
                        <div class="form-group marb8 ">
                            <label>密&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;码</label>
                            <input type="password" id="id_password" name="password"  value="None" placeholder="请输入6-20位非中文字符密码" />
                        </div>
                        <div class="form-group marb8 captcha1 ">
                            <label>验&nbsp;证&nbsp;码</label>
                           {{user_register_form.captcha}}
                        </div>
                        <div class="error btns" id="jsEmailTips">
                            {{ msg }}
                            {% for key,err in user_register_form.errors.items %}
                                {{ err }}
                            {% endfor %}

                        </div>
                        <div class="auto-box marb8">
                        </div>
                        <input class="btn btn-green" id="jsEmailRegBtn" type="submit" value="注册并登录" />
                    </form>
                </div>
                <p class="form-p">已有账号？<a href="login.html">[立即登录]</a></p>
            </div>
        </div>
    </div>
</section>

<input id="isLogin" type="hidden" value="False"/>
<script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/unslider.js' %}" type="text/javascript"></script>
<script src="{% static 'js/validateDialog.js' %}"  type="text/javascript"></script>
<script src="{% static 'js/login.js' %}"  type="text/javascript"></script>
</body>
</html>

templates/users/usercenter-base.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block mycss %}{% static '' %}
    <link rel="stylesheet" type="text/css" href="{% static 'js/plugins/queryCity/css/cityLayout.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/lq.datetimepick.css' %}"/>
    {% block mycss1 %}{% endblock %}
{% endblock %}
{% block middle %}
    <div class="middle">
        <div class="wp">
            <a href="/"><img class="fl" src="{% static 'images/logo1.png' %}"/></a>
            <h1>我的谷粒教育网</h1>
        </div>
    </div>
{% endblock %}

{% block content %}
    <section>
        <div class="wp">
            <ul  class="crumbs">
                <li><a href="/">首页</a>></li>
                <li><a href="{% url 'users:user_info' %}">个人中心</a>></li>
                <li>{% block breach %}{% endblock %}</li>
            </ul>
        </div>
    </section>

    <section>
	<div class="wp list personal_list">
	<div class="left">
        <ul>
            <li class="active2"><a href="usercenter-info.html">个人资料</a></li>
            <li ><a href="usercenter-mycourse.html">我的课程</a></li>
            <li ><a href="usercenter-fav-course.html">我的收藏</a></li>
            <li >
                <a href="usercenter-message.html" style="position: relative;">
                    我的消息
                </a>
            </li>
        </ul>
	</div>

    {% block right %}

    {% endblock %}

	</div>
</section>

    {% block  dialog %}
        <div class="dialog" id="jsDialog">
            <div class="resetpwdbox dialogbox" id="jsResetDialog">
                <h1>修改密码</h1>
                <div class="close jsCloseDialog"><img src="{% static 'images/dig_close.png' %}"/></div>
                <div class="cont">
                    <form id="jsResetPwdForm" autocomplete="off">
                        <div class="box">
                            <span class="word2" >新&nbsp;&nbsp;密&nbsp;&nbsp;码</span>
                            <input type="password" id="pwd" name="password1" placeholder="6-20位非中文字符"/>
                        </div>
                        <div class="box">
                            <span class="word2" >确定密码</span>
                            <input type="password" id="repwd" name="password2" placeholder="6-20位非中文字符"/>
                        </div>
                        <div class="error btns" id="jsResetPwdTips"></div>
                        <div class="button">
                            <input id="jsResetPwdBtn" type="button" value="提交" />
                        </div>
                        <input type='hidden' name='csrfmiddlewaretoken' value='DaP7IUKm9FA9nELA9YUlYYWpyIDdCiIP' />
                    <input type='hidden' name='csrfmiddlewaretoken' value='799Y6iPeEDNSGvrTu3noBrO4MBLv6enY' />
                    </form>
                </div>
            </div>
            <div class="dialogbox changeemai1 changephone" id="jsChangeEmailDialog">
                <h1>修改邮箱</h1>
                <div class="close jsCloseDialog"><img src="{% static 'images/dig_close.png' %}"/></div>
                <p>请输入新的邮箱地址</p>
                <form id="jsChangeEmailForm" autocomplete="off">
                    <div class="box">
                        <input class="fl change_email" name="email" id="jsChangeEmail" type="text" placeholder="输入重新绑定的邮箱地址">
                    </div>
                    <div class="box">
                        <input class="fl email_code" type="text" id="jsChangeEmailCode" name="code" placeholder="输入邮箱验证码">
                        <input class="getcode getting" type="button" id="jsChangeEmailCodeBtn" value="获取验证码">
                    </div>
                    <div class="error btns change_email_tips" id="jsChangeEmailTips" >请输入...</div>
                    <div class="button">
                        <input class="changeemai_btn" id="jsChangeEmailBtn" type="button" value="完成"/>
                    </div>
                    <input type='hidden' name='csrfmiddlewaretoken' value='DaP7IUKm9FA9nELA9YUlYYWpyIDdCiIP' />
                <input type='hidden' name='csrfmiddlewaretoken' value='799Y6iPeEDNSGvrTu3noBrO4MBLv6enY' />
                </form>
            </div>
        </div>
        <div class="bg" id="dialogBg"></div>
    {% endblock %}
{% endblock %}

{% block footer %}

{% endblock %}

{% block myjs %}
    <script src='{% static 'js/plugins/jquery.upload.js' %}' type='text/javascript'></script>
    <script src="{% static 'js/validate.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/deco-user.js' %}"></script>
{% endblock %}

templates/users/usercenter-info.html
{% extends 'users/usercenter-base.html' %}

{% block title %}
    个人信息- 谷粒教育网
{% endblock %}

{% block breach %}
    个人资料
{% endblock %}

{% block right %}
    <div class="right">
		<div class="personal_des ">
			<div class="head" style="border:1px solid #eaeaea;">
				<h1>个人信息</h1>
			</div>
			<div class="inforcon">
				<div class="left" style="width:242px;">
                    <iframe id='frameFile' name='frameFile' style='display: none;'></iframe>
                    <form class="clearfix" id="jsAvatarForm" enctype="multipart/form-data" autocomplete="off" method="post" action="{% url 'users:user_change_image' %}" target='frameFile'>
                        <label class="changearea" for="avatarUp">
                            <span id="avatardiv" class="pic">
                                <img width="100" height="100" class="js-img-show" id="avatarShow" src="{{ MEDIA_URL }}{{ request.user.image }}"/>
                            </span>
                            <span class="fl upload-inp-box" style="margin-left:70px;">
                                <span class="button btn-green btn-w100" id="jsAvatarBtn">修改头像</span>
                                <input type="file" name="image" id="avatarUp" class="js-img-up"/>
                            </span>
                        </label>
                        {% csrf_token %}
                    </form>
                    <div style="border-top:1px solid #eaeaea;margin-top:30px;">
                        <a class="button btn-green btn-w100" id="jsUserResetPwd" style="margin:80px auto;width:100px;">修改密码</a>
                    </div>
				</div>
				<form class="perinform" id="jsEditUserForm" autocomplete="off">
					<ul class="right">
						<li>昵&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;称：
                           <input type="text" name="nick_name" id="nick_name" value="{{ request.user.nick_name|default_if_none:"" }}" maxlength="10">
                            <i class="error-tips"></i>
                        </li>
						<li>生&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;日：
                           <input type="text" id="birth_day" name="birday" placeholder="请输入你的生日"  value="{{ request.user.birthday|default_if_none:"" }}" readonly="readonly"/>
                            <i class="error-tips"></i>
						</li>
						<li>性&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;别：
                                <label>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="radio" name="gender" value="boy" {% if request.user.gender == 'boy' %} checked="checked" {% endif %}>男</label>
                                <label>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="radio" name="gender" value="girl"{% if request.user.gender == 'girl' %} checked="checked"{% endif %}>女</label>
						</li>
						<li class="p_infor_city">地&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;址：
                            <input type="text" name="address" id="address" placeholder="请输入你的地址" value="{{ request.user.address|default_if_none:"" }}" maxlength="10">
						    <i class="error-tips"></i>
                        </li>
						<li>手&nbsp;&nbsp;机&nbsp;&nbsp;号：
                            <input type="text" name="mobile" id="mobile" placeholder="请输入你的手机号码" value="{{ request.user.phone|default_if_none:"" }}" maxlength="11">
                        </li>
                        <li>邮&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;箱：
                        	<input class="borderno" type="text" name="email" readonly="readonly" value="{{ request.user.email|default_if_none:"" }}"/>
                            <span class="green changeemai_btn">[修改]</span>
                    	</li>
						<li class="button heibtn">
							<input type="button" id="jsEditUserBtn" value="保存">
						</li>
					</ul>
                    <input type='hidden' name='csrfmiddlewaretoken' value='799Y6iPeEDNSGvrTu3noBrO4MBLv6enY' />
				</form>
			</div>
		</div>
	</div>
{% endblock %}

{% block myjs1 %}
    <script>
        $(function () {
            $('#jsEditUserBtn').click(function () {
                
            })
        })

    </script>
{% endblock %}